---
# This playbook follows the standard Scylla rolling restart procedure described at https://docs.scylladb.com/operating-scylla/procedures/config-change/rolling_restart/
# This playbook expects at least Scylla version 2021, which has seedless feature
# The play must be run with the --limit argument, specifying either "all" or a list of node IPs

- name: Rolling restart across a Scylla cluster - restart all the machines in limit list
  hosts: scylla
  serial: 1
  become: true
  gather_facts: false
  tasks:
    - name: checking limit arg
      fail:
        msg: "You must use -l or --limit. To restart the entire cluster, use -l 'all'"
      when: ansible_limit is not defined

    - name: register scylla listen address
      shell: |
        grep '^listen_address:' /etc/scylla/scylla.yaml |awk '{ print $2 }'
      register: listen_address

    - name: run nodetool drain
      shell: |
        nodetool drain

    - name: wait for DRAIN to complete
      shell: |
        journalctl -u scylla-server --since "1 minute ago" | grep 'storage_service - DRAINED:'
      retries: 300
      delay: 1
      register: drain_result
      until: drain_result.rc == 0
      ignore_errors: true

    - name: Stop Scylla service
      service:
        name: scylla-server
        state: stopped

    - name: Reboot host and wait for it to restart
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

    - name: wait for the cluster to become healthy
      shell: |
        nodetool status|grep "{{ listen_address.stdout }}" | grep '^UN'
      register: node_status
      until: node_status.rc == 0
      retries: 300
      delay: 1
