---
# Usage:
# Add the new nodes to the existing ansible inventory under [new_nodes]
# and run this playbook using the same variable settings as were used for the original cluster
# new_nodes should be a list containing new node addresses
# After the run is finished, update the inventory moving the new nodes into the [scylla] group

- name: Add Scylla node(s)
  hosts: new_nodes
  become: true
  vars:
    full_inventory: false
    # variables for the Scylla node role
    # Please use the same parameters as were used for the rest of the existing cluster

  roles:
    - ansible-scylla-node

- name: Run cleanup on the old nodes
  hosts: scylla
  gather_facts: false
  serial: 1
  tasks:
    - name: Run cleanup
      script:  files/repair.sh





